permalink: /:year:month:day/:title
url: #Demon's
baseurl: /project

# variables
name: Demon's
description: This site is made to get information on Demon's and evil sprite's etc.
google_verification: null


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]

# Sass
sass:
  style: :compressed
  sass_dir: _sass

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable : true